### ISSUE TITLE
Bundled Tags not showing up

### ISSUE THREAD

**Issue by adwindhot** [Propheus/SG-Game-Tags#2]
only Bundled Tags not showing up.
![qq 20160807103107](https://cloud.githubusercontent.com/assets/20881848/17460110/5a9b2cf0-5c8a-11e6-9f9a-48cf1d3c97d1.png)
![qq 20160807103158](https://cloud.githubusercontent.com/assets/20881848/17460114/5f1349ca-5c8a-11e6-9f95-8012d9c3d3b6.png)
Google Chrome version 52.0.2743.116 m

**Comment by christhofer** [comment]
It works just fine for me
Try reload the page, press f12, and go to console tab to see if there is any error in there.

**Comment by adwindhot** [comment]
sir,Very strange, not error.

**Comment by christhofer** [comment]
@_@
Maybe try factory reset / reinstall the script...

**Comment by adwindhot** [comment]
![default](https://cloud.githubusercontent.com/assets/20881848/17460253/6864fd6a-5c90-11e6-942f-6006ec351f75.png)
New discovery.Why ?

**Comment by christhofer** [comment]
For wishlist, you are not logged in to steam via browser

For bundle list.... your browser didn't get correct list from my server. It can be because your browser failed to load data from my server.
Can you open this page? http://ruphine.esy.es/steamgifts/GetBundleStatus.php
the script requests bundle list from there.

I did make it if invalid json bundle list error appears, reloading page will request again and should fix that error...

**Comment by adwindhot** [comment]
I try to open the page ,but not work ,That's why.

**Comment by christhofer** [comment]
You can't open my site?
What error you get?
Do you use any addons that might block some sites maybe??

**Comment by adwindhot** [comment]
Network operators may shield some site.
I am very sorry but thank your patience.
![default](https://cloud.githubusercontent.com/assets/20881848/17460329/9828b25a-5c93-11e6-9cb1-8bf4f166882d.png)
