### ISSUE TITLE
Script stop working?

### ISSUE THREAD

**Issue by Hope-UwU** [Propheus/SG-Game-Tags#3]
It used to work fine for me but it stopped working for me for quite some time now.
Here's the list of other scripts I have installed http://i.imgur.com/yOwHgrY.png

**Comment by Hope-UwU** [comment]
Never mind. For some reason it started working again after I uninstall and reinstall it again :/

**Comment by christhofer** [comment]
@5630525021-VD sorry, I don't have time to work on this anymore, so if SG or Steam changed something that breaks the script, I can't fix it ASAP.
Bundle list tag is not updated since 2 months ago, idk why but seems like SG blocks my server every time it scans bundle pages. The scan always stops at 2nd or 3rd page.
My server bundled games : 7688
SG bundled games : 7991 (320 pages)

 I've tried to fix it when I barely had a time to do that, but to no avail.
Other tags should works just fine as long Steam doesn't change its API.

**Comment by Hope-UwU** [comment]
@Propheus Wishlist tag is the one I really want since it help speed up browsing speed through train. Really appreciate your work!

By the way I also use 2 scripts which basically collections of other scripts - [SFTfrog](https://github.com/bberenz/sgtfrog) and [ESGST](https://github.com/revilheart/ESGST). Would you mind if I request them the same feature of your script?

**Comment by christhofer** [comment]
@5630525021-VD Please do, so that I don't have to worry about my script anymore. XD
